version: "3.3"
services:
  mongodb:
    image: mongo:3.4
    container_name: mock-easy-mongo
    volumes:
      - type: bind
        source: ./data/db # 数据库文件存放地址，根据需要修改为本地地址
        target: /data/db
  web:
    image: easymock/easymock
    command: /bin/bash -c "npm run build && npm start"
    container_name: mock-easy
    links:
      - mongodb:mongodb
    ports:
      - 7300:7300
    volumes:
      - type: bind 
        source: ./logs # 日志地址，根据需要修改为本地地址
        target: /home/easy-mock/easy-mock/logs
      - type: bind
        source: ./production.json # 配置地址，请使用本地配置地址替换
        target: /home/easy-mock/easy-mock/config/production.json
      - type: bind
        source: ./package.json
        target: /home/easy-mock/easy-mock/package.json
  swagger:
    container_name: mock-swagger
    image: swaggerapi/swagger-editor
    ports: 
      - 8001:8080
